DW-28: Add task layout
Bartosiki/DW-Flutter-App pull request #48
Opened 2024-05-05 19:02 UTC by BartoszChadrys

2024-05-05 19:09 UTC, IgorJonski commented on lib/components/screen_description.dart
> +  const ScreenDescription({super.key, required this.description, this.trailingIcon});
przecinek po this.trailingIcon

2024-05-05 19:12 UTC, olekgolus11 requested changes

2024-05-05 19:12 UTC, olekgolus11 commented on lib/components/tasks/task_card.dart
> +      ),
,

2024-05-05 19:12 UTC, olekgolus11 commented on lib/constants/strings.dart
> +  }
@IgorJonski  tak moze byc?

2024-05-05 19:12 UTC, olekgolus11 commented on lib/views/home/screens/tasks/your_tasks_subpage.dart
>      final tasks = ref.watch(tasksProvider);
gdzies bym te pointy wyjebal zebysmy o tym nie zapomnieli

2024-05-05 19:14 UTC, IgorJonski requested changes

2024-05-05 19:14 UTC, IgorJonski commented on lib/components/screen_description.dart
> +          ),
Można zrobić jednego ifa, a te 2 widgety zapiąć w dodatkową Column

2024-05-05 19:14 UTC, IgorJonski commented on lib/components/tasks/task_card.dart
> +      super.key});
przecinek po super.key

2024-05-05 19:14 UTC, IgorJonski commented on lib/components/tasks/task_card.dart
> +            )),
przecinek między ))

2024-05-05 19:14 UTC, IgorJonski commented on lib/components/tasks/task_list.dart
> +  const TaskList({super.key, required this.tasks});
przecinek po this.tasks

2024-05-05 19:14 UTC, IgorJonski commented on lib/views/home/screens/tasks/your_tasks_subpage.dart
> +    final points = 5;
co to jest?

2024-05-05 19:14 UTC, IgorJonski commented on lib/views/home/screens/tasks/your_tasks_subpage.dart
> +              padding: const EdgeInsets.only(left: 16, right: 16),
daj EdgeInsets.symmetric(horizontal: 16) zamiast tą samą wartość na left i right

2024-05-05 19:14 UTC, IgorJonski commented on lib/views/home/screens/tasks/your_tasks_subpage.dart
> +                            Colors.white, BlendMode.srcIn
przecinek na końcu

2024-05-05 19:14 UTC, IgorJonski commented on lib/views/home/screens/tasks/your_tasks_subpage.dart
> +                        fontSize: 16),
przecinek po 16

2024-05-05 19:14 UTC, IgorJonski commented on lib/views/home/screens/tasks/your_tasks_subpage.dart
> +                  Expanded(child: TaskList(tasks: tasks))
przecinek!

2024-05-06 07:32 UTC, olekgolus11 approved these changes
![image](https://github.com/Bartosiki/DW-Flutter-App/assets/84678175/31196a4f-88b3-4946-a88c-18a3cbc53455)

2024-05-07 19:11 UTC, IgorJonski requested changes
wiesz co :D

2024-05-07 19:11 UTC, IgorJonski commented on lib/components/screen_description.dart
> +                    fontSize: 16))),
, ,

2024-05-07 19:11 UTC, IgorJonski commented on lib/components/screen_description.dart
> +              IconButton(iconSize: 30, onPressed: null, icon: trailingIcon!),
,

2024-05-07 19:11 UTC, IgorJonski commented on lib/components/tasks/task_card.dart
> +      super.key,});
super.key na górze, przecinki

2024-05-07 19:11 UTC, IgorJonski commented on lib/components/tasks/task_card.dart
> +                      color: Colors.white, fontWeight: FontWeight.bold
,

2024-05-07 19:11 UTC, IgorJonski commented on lib/components/tasks/task_card.dart
> +                      fontSize: 12
,

2024-05-07 19:11 UTC, IgorJonski commented on lib/components/tasks/task_card.dart
> +                  )
,

2024-05-07 19:11 UTC, IgorJonski commented on lib/components/tasks/task_list.dart
> +          points: task.points
,

2024-05-07 19:11 UTC, IgorJonski commented on lib/views/home/screens/tasks/your_tasks_subpage.dart
> +                      )
,

2024-05-07 20:21 UTC, IgorJonski approved these changes
może być
😼

2024-05-07 20:21 UTC, merged