DW-31: QR Scanner layout and functionality
Bartosiki/DW-Flutter-App pull request #51
Opened 2024-05-09 22:17 UTC by IgorJonski

2024-05-10 07:54 UTC, BartoszChadrys requested changes
Reszta wygląda git
<img width="235" alt="Zrzut ekranu 2024-05-10 o 09 54 23" src="https://github.com/Bartosiki/DW-Flutter-App/assets/97181425/ee9f0fd0-7a84-4732-aacf-c0305b14c000">

2024-05-10 07:54 UTC, BartoszChadrys commented on ios/Podfile.lock
>      - abseil/base/config
Niepotrzebnie dodany plik

2024-05-10 07:54 UTC, BartoszChadrys commented on ios/Runner.xcodeproj/project.pbxproj
>  				F19514DD4D2BFAF257133EB0 /* Pods-RunnerTests.profile.xcconfig */,
Ten plik też niepotrzebny

2024-05-10 07:54 UTC, BartoszChadrys commented on pubspec.lock
>      source: hosted
kolejny plik do wywalenia

2024-05-10 10:28 UTC, olekgolus11 approved these changes
Ok bro
![image](https://github.com/Bartosiki/DW-Flutter-App/assets/84678175/8c13df81-9144-40f9-a262-1b6c4bf3f6f4)

2024-05-10 23:34 UTC, IgorJonski commented on pubspec.lock
>      source: hosted
jesteś pewien że pubspec.lock nie jest potrzebny?

2024-05-10 23:36 UTC, IgorJonski commented on ios/Runner.xcodeproj/project.pbxproj
>  				F19514DD4D2BFAF257133EB0 /* Pods-RunnerTests.profile.xcconfig */,
<img width="644" alt="image" src="https://github.com/Bartosiki/DW-Flutter-App/assets/71559210/ff60b1f5-2baf-421b-a272-2fce5856fce3">

???

2024-05-11 11:02 UTC, BartoszChadrys approved these changes
Teraz git 😃

2024-05-11 11:04 UTC, merged