Add language change, event categories and descriptions
Bartosiki/DW-Flutter-App pull request #80
Opened 2024-05-24 19:03 UTC by Gujansko

Closes #66 
Closes #81 
Closes #65 

**Ten pr dodaje możliwość tłumaczenia aplikacji na różne języki. Aktualnie dostępne są angielski i polski.
Wszystkie stringi w aplikacji są aktualnie tłumaczone.**

### Poradnik co zrobić jak chce dodać nowy string.

1. Otwieram plik strings.dart, dodaje nowe pole final i to samo pole w konstruktorze.
![image](https://github.com/Bartosiki/DW-Flutter-App/assets/106811447/e66bd1fa-9a2c-457a-be9f-31b1a43b3b45)
![image](https://github.com/Bartosiki/DW-Flutter-App/assets/106811447/507614db-e69c-4c7b-b3d9-cc9285b16768)
2. Automatycznie pojawią się błędy w plikach strings_pl i strings_en. Musimy dodać wartości dodanych pól w klasie podstawowej strings.
![image](https://github.com/Bartosiki/DW-Flutter-App/assets/106811447/1f50eddf-be9d-4f3f-aaed-462efb790f6b)
![image](https://github.com/Bartosiki/DW-Flutter-App/assets/106811447/7e0f6d44-bd77-4ce2-a517-36501a47339c)
3. Podepnij się refem do aktualnie wybranego języka aplikacji w pliku w którym chcesz użyć nowego stringa.
`final selectedLanguage = ref.watch(languageProvider);`
`final strings = selectedLanguage == LanguageSettings.defaultLanguage
        ? StringsEn.en
        : StringsPl.pl;`
3a. nie masz dostępu do refa? możliwe że musisz dać widget Consumer jako wrapper
`return Consumer(`
      `builder: (context, ref, _) {`
        `final selectedLanguage = ref.watch(languageProvider);`
        `final strings = selectedLanguage == LanguageSettings.defaultLanguage
            ? StringsEn.en
            : StringsPl.pl;`
4. Użyj wartości tekstowej
`Text(strings.points)`

**Język zmieniamy w profile screen i zapisuje się on w shared preferences. Próbowałem zrobić tak żeby język przy włączeniu apki był polski jeżeli masz polski język systemu i angielski jeżeli inny. Default to również angielski ale nie jestem pewny czy to działa na pewno nic mi się nie wywaliło.**
![Bez tytułu](https://github.com/Bartosiki/DW-Flutter-App/assets/106811447/4808585a-0a31-4c2b-a568-7e241ee6fb08)

2024-05-24 20:29 UTC, IgorJonski requested changes
Create string

2024-05-24 20:29 UTC, IgorJonski commented on lib/screens/home/screens/assistant_screen.dart
> +        : StringsPl.pl;
Create stringsProvider instead of repeating these 4 lines in every widget

2024-05-24 20:29 UTC, IgorJonski commented on lib/screens/home/home_screen.dart
> +              style: const TextStyle(fontWeight: FontWeight.w600),
No need for consumer in ConsumerWidget or ConsumerStatefulWidget, fix in all files

2024-05-25 09:17 UTC, BartoszChadrys approved these changes
Dobra robota 

![image](https://github.com/Bartosiki/DW-Flutter-App/assets/97181425/21864670-45a7-4eff-9180-9eccaed7c7d6)

2024-05-25 09:17 UTC, BartoszChadrys commented on lib/components/tasks/sort_toggle_button.dart
> +    return Consumer(
Chyba łatwiej zamienić cały widget na ConsumerStatefulWidget

2024-05-25 09:22 UTC, Gujansko commented on lib/components/tasks/sort_toggle_button.dart
> +    return Consumer(
Ale po co iść na łatwiznę

2024-05-26 17:37 UTC, olekgolus11 approved these changes
![image](https://github.com/Bartosiki/DW-Flutter-App/assets/84678175/204ddd33-2f75-4593-8c3c-9c13b6449d8f)

czemu ty nazywasz brancha po polsku z polskimi literami to jest grzech pierdolony

2024-05-26 17:39 UTC, Gujansko commented
> ![image](https://private-user-images.githubusercontent.com/84678175/333898656-204ddd33-2f75-4593-8c3c-9c13b6449d8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NDU0MTAsIm5iZiI6MTcxNjc0NTExMCwicGF0aCI6Ii84NDY3ODE3NS8zMzM4OTg2NTYtMjA0ZGRkMzMtMmY3NS00NTkzLThjM2MtOWMxM2I2NDQ5ZDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE3MzgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYmI4NGUxNDZkMzI2ODk1YTA4YzEzOGEwZWYzMDM5NTg0OGIyZmRiMTJhNTA5MTkxNzBkYWIzYTBlNWViMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f26VXItdVNKpvZzoqnikyqoTX3ILFIBgHW7eX87K4Iw)
> 
> czemu ty nazywasz brancha po polsku z polskimi literami to jest grzech pierdolony

Byku ja w issue kliknąłem stwórz mi brancha więc zaciągnął jakieś polskie znaki z issue i się taki stworzył

2024-05-27 19:24 UTC, IgorJonski approved these changes

2024-05-27 19:24 UTC, merged